"""Add personas and unidad_persona

Revision ID: 13ac3ff8dff7
Revises: e8729272a5c5
Create Date: 2025-11-20 13:46:46.017255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ac3ff8dff7'
down_revision = 'e8729272a5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('identificacion', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('unidad_persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('es_propietario', sa.Boolean(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.Column('es_actual', sa.Boolean(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidad_persona')
    op.drop_table('personas')
    # ### end Alembic commands ###
