"""agrega unique constraint proyecto_id nombre en unidad

Revision ID: 3dc7d715e0a8
Revises: ad5a38a592d1
Create Date: 2026-03-23 10:09:40.751468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc7d715e0a8'
down_revision = 'ad5a38a592d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_unidad_proyecto_nombre', ['proyecto_id', 'nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unidad_proyecto_nombre', type_='unique')

    # ### end Alembic commands ###
