"""Add etapas model

Revision ID: 562190e6035c
Revises: f32048706bf8
Create Date: 2025-11-19 23:34:12.692085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '562190e6035c'
down_revision = 'f32048706bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('etapas')
    # ### end Alembic commands ###
