"""Add monto_mantenimiento to etapas

Revision ID: ad5a38a592d1
Revises: 13ac3ff8dff7
Create Date: 2025-11-21 19:34:45.973050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5a38a592d1'
down_revision = '13ac3ff8dff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_mantenimiento', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapas', schema=None) as batch_op:
        batch_op.drop_column('monto_mantenimiento')

    # ### end Alembic commands ###
