"""add comunicaciones table

Revision ID: d82e7712014c
Revises: 3dc7d715e0a8
Create Date: 2026-05-20 08:11:21.818135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82e7712014c'
down_revision = '3dc7d715e0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=False),
    sa.Column('email_destino', sa.String(length=150), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('incluye_estado_cuenta', sa.Boolean(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicaciones')
    # ### end Alembic commands ###
