"""Restore etapa_id in unidades

Revision ID: e8729272a5c5
Revises: 562190e6035c
Create Date: 2025-11-19 23:51:30.702627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8729272a5c5'
down_revision = '562190e6035c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etapa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'etapas', ['etapa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etapa_id')

    # ### end Alembic commands ###
