"""Adjuntos ahora guardan archivo en disco

Revision ID: f32048706bf8
Revises: 1ac57ad4e1e0
Create Date: 2025-11-19 15:50:50.997870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32048706bf8'
down_revision = '1ac57ad4e1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjuntos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=300), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjuntos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.BLOB(), nullable=False))
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
